### ISSUE TITLE
Requests to api.mixpanel.com are blocked by CORS policy

### ISSUE THREAD

**Issue by ragnhildlarsen** [cognitedata/reveal-viewer#11]
Version 5.0.7 of Cognite3DViewer:

Receives these messages in the console while running the viewer in our application. Have tried to opt out from logMetrics to see if that removed the messages but that did not help either. 
`public createCognite3DView() {
        this._view = new Cognite3DViewer({logMetrics: false});
    }`

![Screenshot 2019-05-21 at 08 05 14](https://user-images.githubusercontent.com/50363113/58072194-33c3d780-7b9f-11e9-8a81-1065fbcfa6fe.png)

The response in the network panel looks like this: 
`upstream connect error or disconnect/reset before headers`
![Screenshot 2019-05-21 at 08 14 45](https://user-images.githubusercontent.com/50363113/58072637-9669a300-7ba0-11e9-91ec-70530cc43843.png)
![Screenshot 2019-05-21 at 08 19 12](https://user-images.githubusercontent.com/50363113/58072812-27407e80-7ba1-11e9-9fcd-b6d9ec12aab4.png)

Is this an issue on our side? I didn't see these messages yesterday.

**Comment by anderscognite** [comment]
I'm not sure why it happens, but it is explained by https://help.mixpanel.com/hc/en-us/articles/115004511086-CORS-errors.

The reason why `logMetrics: false` does not work is that we do call `mixpanel.init` even if you have logMetrics false, but this is fixed in a later version of the viewer. We do recommend to have logging on as this gives valuable insight in experience of our and your users.

Will close this as it is not a problem, especially not in production. Fix for logMetrics is on its way :)
